/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenprojectc;
import java.util.Scanner;


/**
 *
 * @author b43145
 */
public class lottoprog extends javax.swing.JFrame {
     public static String playerName;
     public static int descision;
      public static double money;
      public static int[] playerNumber;
    /**
     * Creates new form lottoprog
     */
    
    public lottoprog() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dawson's Lotto Machine");

        button1.setText("Start");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel1.setText("Dawson's Lotto Machine");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem1.setText("How to play");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(button1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(button1)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        
//    static void delay(){
//        try {
//            Thread.sleep(1500L);    // one and a half second, increase value to increase the delay
//        }
//        catch (Exception e) {}
//    }
user();
Scanner reader = new Scanner(System.in);     
descision = 0;
  while(descision != 2){
      ticket();
      playerNumbers();
  }
 
    }//GEN-LAST:event_button1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         help f = new help();
       f.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
public void user(){
     Scanner reader = new Scanner(System.in);  // Reading from System.in
    System.out.println("Dawson's LottoMachine ");       //Displaying Dawson's LottoMachine at the start of the program
    System.out.println("Enter your name ");       //Displaying Dawson's LottoMachine at the start of the program

     playerName = reader.next();
    System.out.println("Enter your initial deposit "); 
    String initial = reader.next();
     System.out.println("Enter your age ");       //Displaying Dawson's LottoMachine at the start of the program
    int age = reader.nextInt();
    if (age<18){
         System.out.println("You are too young to play! ");
         System.exit(0);
    };
}


public void ticket(){
    Scanner reader = new Scanner(System.in);
    
   System.out.println("Enter which ticket you will like to purchase");
   System.out.println("(3.00 = $3, 5.00 = $5, 10.00 = $10)");
   money = reader.nextDouble();
   System.out.println("Do you have a discount code?");
     System.out.println("Press Y for yes or press N for no");
   String discount = reader.next();
   double perc = 0;
   if(discount == "y" || discount == "Y" ){
       perc = 0.5;
   }
   else{
       perc = 0;
   }
}

public void playerNumbers(){
     Scanner reader = new Scanner(System.in);
 System.out.println("Enter numbers between 1 and 25");           //Displaying Enter numbers between 1 and 25
            playerNumber = new int[6];
            for(int i=1; i<6; i++)                                          //for player numbers
            {
                String s = "";
                switch(i)
                {
                    case 1: s = "st"; break;                                //when i is 1 the suffix st will appear behind i
                    case 2: s = "nd"; break;                                //when i is 2 the suffix nd will appear behind i
                    case 3: s = "rd"; break;                                //when i is 3 the suffix rd will appear behind i
                    default: s = "th"; break;                               //when i is 4 and 5 the suffix th will appear behind i
                }
                System.out.println("Enter your " + i + s + " number");
                //Displaying Enter your number and i and the suffix will be shown in between

                playerNumber[i] = reader.nextInt();                       
                while(playerNumber[i] > 25 || playerNumber[i] < 1){         //If the player number is larger than or smaller than 1 the program will continue to ask for the right input
                    System.out.print("Invalid Number. Try again: ");
                    playerNumber[i] = reader.nextInt();
                }
            }
 int[] lottoNumber = new int[5];           //Generating lotto number from 1 to 25
            {  
                lottoNumber[0] = (int) ((25 * Math.random()) + 1);  
                lottoNumber[1] = (int) ((25 * Math.random()) + 1);  
                lottoNumber[2] = (int) ((25 * Math.random()) + 1);  
                lottoNumber[3] = (int) ((25 * Math.random()) + 1);  
                lottoNumber[4] = (int) ((25 * Math.random()) + 1);  
            }

            lottoNumber[0] = (int) ((25 * Math.random()) + 1);         //first number drawn
            int i = 1;                                                 //setting i to 1
            boolean found = false;                                     //creating variable found of type boolean
            do{         
                lottoNumber[i] = (int) ((25 * Math.random()) + 1);     //creating the first lotto number
                for (int j=0;j<i;j++){                                 
                    if (lottoNumber[i] == lottoNumber[j]) found=true;
                }
                if (found == false)i++;
            }while (i<5);

            System.out.println("Lottery Numbers: ");                     //Displaying the words lottery numbers
            for(int k=0; k<5; k++)  
            {  
                
                System.out.println(lottoNumber[k] + " " );               //Displaying lottery numbers
            }
            
            
            
            //checking amount of numbers guessed by the user    
            i = 0;                                                       //setting i to 0 
            int same = 0;                                                // setting same to 0
            do{
                for (int j=0;j<5;j++){
                    if (lottoNumber[i] == playerNumber[j]) same++;
                }
                i++;
            }while (i<5);  
            System.out.println("Amount of same numbers: "+ same);         //Displaying Amount of same numbers and the contents of same will be displayed
double winnings = 0;     //Setting winnings to 0
            if(money == 3.00 && same >=1){                        //If the money is 3.50 and same is larger than one or equal to 1
                winnings = same  * 4.25;                                      
                System.out.println(playerName+ ", You have won:");
                System.out.println(" €" + winnings);
                System.out.println("Your profit is: $" + Math.round(winnings - money));

            }
            else if(money == 5.00 && same >=1){                //if the money is 5.00 and same is larger than one or equal to 1   
                winnings = same * 6.35;
                System.out.println(playerName + ", You have won:");
                System.out.println(" €" + winnings);
                System.out.println("Your profit is: $" + Math.round(winnings - money));
            }
            else if(money == 10.00 && same >=1){                //if the money is 10.00 and same is larger than one or equal to 1
                winnings = same *  13.45;
                System.out.println(playerName + ", You have won:");
                System.out.println(" €" + winnings);
                System.out.println("Your profit is: $" + Math.round(winnings - money));
            }
            else if(money == 3.50 && same <1){                  //if the money is 3.50 and same is smaller than one   
                System.out.println(playerName + ", none of your numbers have been drawn, better luck next time!");
            }
            else if(money == 5.00 && same <1){                  //if the money is 5.00 and same is smaller than one   
                System.out.println(playerName + ", none of your numbers have been drawn, better luck next time!");
            }
            else if(money == 10.00 && same <1){                 //if the money is 10.00 and same is smaller than one   
                System.out.println(playerName + ", none of your numbers have been drawn,better luck next time!");
            } 
            else if(money == 3.50 && same == 5){                  //if the money is 3.50 and same is equal to five 
                System.out.println(playerName + ", Congratulations!! You have won the jackpot prize"); //display player name and the text  Congratulations!! You have won the jackpot prize
                System.out.println(" €" + winnings);                                                     //display euro sign and winnings
                System.out.println("Your profit is: $" + Math.round(winnings - money));          //display your profit is and subtract player1.money from winnings
            }
            else if(money == 5.00 && same == 5){                
                System.out.println(playerName + ", Congratulations!! You have won the jackpot prize");
                System.out.println(" €" + winnings);
                System.out.println("Your profit is: $" + Math.round(winnings - money));
            }
            else if(money == 10.00 && same == 5){               
                System.out.println(playerName + ", Congratulations!! You have won the jackpot prize");
                System.out.println(" €" + winnings);
                System.out.println("Your profit is: $" + Math.round(winnings - money));
            } 
            
            
            System.out.println("Press 1 to play again, press 2 to exit");
        descision = reader.nextInt();
        switch(descision){
            case 1: descision = 1;
            break;
            case 2: 
            descision = 2;
            System.exit(0);
        }
        
  }

  








    /**
     * @param args the command line arguments
     */
    public  void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lottoprog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lottoprog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lottoprog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lottoprog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new lottoprog().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
